# Do not edit. Generated by the configure script.
export PATH:=/workspaces/node_x86_64-2/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.10
PREFIX=/usr/local
